import React, { useState } from 'react'
import TabNavigation from './components/TabNavigation'
import DailyPreview from './pages/DailyPreview'
import SwitchupDiff from './pages/SwitchupDiff'
import WeeklySnapshot from './pages/WeeklySnapshot'
import ErrorBoundary from './components/ErrorBoundary'
import './App.css'

type TabType = 'preview' | 'compare' | 'weekly'

function App() {
  const [activeTab, setActiveTab] = useState<TabType>('preview')

  const renderActiveTab = () => {
    switch (activeTab) {
      case 'preview':
        return <DailyPreview />
      case 'compare':
        return <SwitchupDiff />
      case 'weekly':
        return <WeeklySnapshot />
      default:
        return <DailyPreview />
    }
  }

  return (
    <ErrorBoundary>
      <div className="min-h-screen bg-gray-50">
        {/* Header */}
        <header className="bg-white shadow-sm border-b">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between h-16">
              <div className="flex items-center">
                <span className="text-2xl">🍅</span>
                <h1 className="ml-2 text-xl font-bold text-gray-900">
                  Tamatar-Bhai MVP
                </h1>
              </div>
              <div className="text-sm text-gray-500">
                AI-powered food insights
              </div>
            </div>
          </div>
        </header>

        {/* Tab Navigation */}
        <TabNavigation activeTab={activeTab} onTabChange={setActiveTab} />

        {/* Main Content */}
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {renderActiveTab()}
        </main>

        {/* Footer */}
        <footer className="bg-white border-t mt-12">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
            <div className="text-center text-sm text-gray-500">
              Generated by OpenAI & StabilityAI • Built with ❤️ for the Tamatar-Bhai community
            </div>
          </div>
        </footer>
      </div>
    </ErrorBoundary>
  )
}

export default App